Repository slack-edge/slack-edge, pull requests merged in 2024-10, with the labels that each got.

#36 Improve app.action payload type handling
  src/app.ts
  src/handler/handler.ts
  src/request/payload/block-action.ts
  src_deno/app.ts
  src_deno/handler/handler.ts
  src_deno/request/payload/block-action.ts
  test/app.test.ts
  test/node-socket-mode/package.json
  test/node-socket-mode/src/app.ts
Labels: bug, enhancement

#38 Update example code for Vercel Edge
  README.md
Labels: documentation

#41 Fix #40 invalid event name
  src/app.ts
  src/request/payload/event.ts
  src_deno/app.ts
  src_deno/request/payload/event.ts
Labels: bug
